name: CI
on: push

jobs:
  ci:
    name: CI
    runs-on: windows-latest
    steps:
      - name: Echo with \n
        shell: bash
        run: |
          echo "abc\ndef"
          echo -e "abc\ndef"
          # printf "abc\ndef"
          echo $SHELL
          curl --location --remote-name https://raw.githubusercontent.com/upleveled/expo-example-winter-2025-eu/main/metroRequire.d.ts
